groups:
  - name: prometheus-self-monitoring
    rules:
      - alert: PrometheusTargetMissing
        expr: up == 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Prometheus target missing"
          description: "Some scrape targets are unreachable."

      - alert: PrometheusConfigReloadFailed
        expr: prometheus_config_last_reload_successful == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Prometheus config reload failed"
          description: "Check configuration file syntax and errors."
