# Save this as k8s/dev/fonapp-app.yaml (recommended GitOps style)
# kubectl apply -f k8s/dev/fonapp-app.yaml -n argocd

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fonapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dainmusty/gnpc-terraform-infra-k8s-web-app.git
    targetRevision: main
    path: k8s/fonapp
  destination:
    server: https://kubernetes.default.svc
    namespace: fonapp
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
