apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: fonapp
  labels:
    app: web-app
    environment: dev
    managed-by: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
        environment: dev
        managed-by: argocd
    spec:
      containers:
        - name: web-app
          image: nanajanashia/k8s-demo-app:v1.0
          ports:
            - containerPort: 3000
          env:
          - name: USER_NAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-usr
          - name: USER_PWD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-pwd
          - name: DB_URL
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: mongo-url
