plugin: aws_ec2
regions:
  - us-east-1  # Set your region
filters:
  tag:Environment: Dev
  instance-state-name: running

keyed_groups:
  - key: tags.Name
    prefix: name

compose:
  ansible_host: private_ip_address  # or use public_ip_address if needed

# Optional: If you want to auto-label the host with its Name tag
hostnames:
  - tag:Name
