---
plugin: aws_ec2
regions:
  - us-east-1
filters:
  tag:Environment: Dev
keyed_groups:
  - key: tags.Name
    prefix: name
hostnames:
  - private-ip-address
compose:
  ansible_host: private_ip_address
