- name: Provision Prometheus data source using template
  template:
    src: prometheus-datasource.yml.j2
    dest: /etc/grafana/provisioning/datasources/prometheus.yml
    mode: '0644'
  notify: Restart Grafana
