---
- name: Setup Prometheus
  hosts: name_Prometheus
  become: true
  tasks:
    - name: Copy Prometheus setup script
      copy:
        src: ../../scripts/prometheus_userdata.sh
        dest: /tmp/prometheus_userdata.sh
        mode: '0755'

    - name: Run Prometheus setup script
      shell: /tmp/prometheus_userdata.sh

- name: Setup Grafana
  hosts: name_Grafana
  become: true
  tasks:
    - name: Copy Grafana setup script
      copy:
        src: ../../scripts/grafana_userdata.sh
        dest: /tmp/grafana_userdata.sh
        mode: '0755'

    - name: Run Grafana setup script
      shell: /tmp/grafana_userdata.sh
