---
- name: Update APT packages
  apt:
    update_cache: yes

- name: Install Prometheus
  apt:
    name: prometheus
    state: present

- name: Enable and start Prometheus
  systemd:
    name: prometheus
    enabled: yes
    state: started

- name: Upload alert.rules.yml
  template:
    src: alert.rules.yml.j2
    dest: /etc/prometheus/alert.rules.yml
    owner: prometheus
    group: prometheus
    mode: '0644'

- name: Restart Prometheus to apply changes
  systemd:
    name: prometheus
    state: restarted
    daemon_reload: yes