name: Kubernetes Destroy by Manual Trigger

on:
  workflow_dispatch: # Manual trigger for kubectl delete

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: effulgencetech-dev

jobs:
  destroy-k8s:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set environment name
      id: env
      run: |
        echo "env=dev" >> $GITHUB_OUTPUT

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

    - name: Destroy Kubernetes Manifests
      run: |
        kubectl delete -f k8s/${{ steps.env.outputs.env }}/ --ignore-not-found
