name: Terraform Destroy | Manual Approval Only

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Type YES to confirm full destroy"
        required: true
        default: "NO"

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: effulgencetech-dev
  DEPLOYMENT_PATH: root-modules/env/dev

permissions:
  contents: read
  id-token: write

jobs:
  Destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    environment:
      name: dev  # Adds manual approval protection (recommended)
    if: github.event.inputs.confirm_destroy == 'YES'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: ${{ env.DEPLOYMENT_PATH }}
        run: terraform init -input=false

      - name: Terraform Destroy
        working-directory: ${{ env.DEPLOYMENT_PATH }}
        run: terraform destroy -auto-approve

      - name: Cleanup confirmation
        run: echo "✅ Terraform infrastructure destroyed successfully."
